//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_new_сriteria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class eternalshow
    {
        public int number { get; set; }
        public System.DateTime date { get; set; }
        public int ID { get; set; }
        public string product_ID { get; set; }
        public int partner_ID { get; set; }
        public string name { get; set; }
        public string partner_name { get; set; }
        public string type { get; set; }
        public string adress { get; set; }
        public int rating { get; set; }
    }
}
