//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_new_сriteria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class postavka_product_partner
    {
        public string product_ID { get; set; }
        public int partner_ID { get; set; }
        public int postavka_ID { get; set; }
    
        public virtual partners partners { get; set; }
        public virtual postavki postavki { get; set; }
        public virtual products products { get; set; }
    }
}
