//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace for_new_сriteria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_extra
    {
        public string material { get; set; }
        public string color { get; set; }
        public int size { get; set; }
        public int type { get; set; }
        public string ID { get; set; }
    
        public virtual product_type product_type { get; set; }
        public virtual products products { get; set; }
    }
}
